# Generated by Django 4.1.2 on 2022-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
