# Generated by Django 4.1.2 on 2022-10-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tasks_deleted_at_alter_projects_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
