# Generated by Django 4.1.2 on 2022-10-25 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_tasks_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
